converted to esm
colorjs/color-name pull request #19
Opened 2021-08-07 11:09 UTC by jimmywarting

Friendlier Deno/browser import without the need for npm

2022-06-26 12:33 UTC, LitoMore requested changes

2022-06-26 12:33 UTC, LitoMore commented on package.json
> +    "node": "12.20"
```suggestion
    "node": ">=12.20"
```

2022-06-26 12:33 UTC, LitoMore commented on test.js
> +import assert from 'assert';
```suggestion
import assert from 'node:assert';
```

2022-11-06 09:58 UTC, alexander-heimbuch commented
Any chance this get's merged? I would highly appreciate esm support :)

2022-11-08 14:30 UTC, merged